### ISSUE TITLE
JTM does not recognise en.json file

### ISSUE THREAD

**Issue by SanMildrid** [MohammedAldosari/json-translations-manager#14]
As suggested I specified the localization folder and added an en.json file.
But this file is somehow not recognised by JTM. When trying to add a new translation I get the error notification: "No Translation in empty workspace"

**Comment by MohammedAldosari** [comment]
first, you have to use the command JTM: Initialize or update JTM configration this command will create or update the jtmConfig.json file on your project.

jtmConfig file will have the location where translation file is located on your project

I hope this will be helpful for you and don't hesitate to contact me if have any inquiry or suggestion

**Comment by SanMildrid** [comment]
Thats exactly what I did. I used the command and the jtmConfig.json file was created within my VSCode: 
```
{
  "translationFolder": "d:\\Projekte\\JTM-test",
  "sort": true
}
```
But I will try to update with the command - maybe this helps.

**Comment by SanMildrid** [comment]
Trying to Update with "JTM: Initialize or update JTM configuration" lead to this errors:
![grafik](https://user-images.githubusercontent.com/85504566/124428907-835cc180-dd6d-11eb-8c9a-9b65d58ade87.png)

![grafik](https://user-images.githubusercontent.com/85504566/124429117-c0c14f00-dd6d-11eb-9c79-e53ebc711852.png)

I will try uninstall and re-install next.

**Comment by MohammedAldosari** [comment]
Try to remove the jtmConfig.json then run the command JTM: Initialize or update JTM configuration this command will create the jtmConfig.json file again on your project.

because the path for translationFolder should be relative to workspace path as the example image below:

![image](https://user-images.githubusercontent.com/22413496/125979620-e064e9f8-47f3-4876-958f-087b80a64517.png)
